# Generated by Django 6.0.2 on 2026-02-26 00:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('categoria', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='categoria',
            name='categoria_imagem',
            field=models.ImageField(blank=True, upload_to='fotos/categorias/'),
        ),
    ]
