# Generated by Django 6.0.4 on 2026-04-16 00:24

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('produto', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Carrinho',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('car_id', models.CharField(blank=True, max_length=20)),
                ('data_criado', models.DateField(auto_now_add=True)),
                ('data_modificado', models.DateField(auto_now=True)),
            ],
        ),
        migrations.CreateModel(
            name='CarItem',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('quantidade', models.IntegerField()),
                ('preco', models.DecimalField(decimal_places=2, max_digits=11)),
                ('produto', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='produto.produto')),
                ('carrinho', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='carrinho.carrinho')),
            ],
        ),
    ]
